version: '2'
networks:
  stack:
    external:
      name: stack
services:
  sample-app:
    image: sample
    networks: ['stack']
    container_name: sample-app
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://sample-mysql:3306/sample?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true
      - ELASTIC_APM_SERVER_URLS=http://apm:8200
    ports:
      - 8080:8080